/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zlaboratorioexamenfinal;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    PSNUsers psn;
    boolean isActivo = false;
    public main() throws IOException {
        initComponents();
        menu.setVisible(true);
        deactivateUser.setVisible(false);
        addUser.setVisible(false);
        addTrophy.setVisible(false);
        playerInfo.setVisible(false);
        psn = new PSNUsers();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addUser = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addUserTF = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        addTrophy = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addTrophyTF = new javax.swing.JTextField();
        addTrophyButton = new javax.swing.JButton();
        backButtonAT = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        nameTrophy = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        trophyType1 = new javax.swing.JTextField();
        juego = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        deactivateUser = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        deactivateUserTF = new javax.swing.JTextField();
        deactivateButton = new javax.swing.JButton();
        backButtonDU = new javax.swing.JButton();
        playerInfo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        content = new javax.swing.JTextArea();
        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addUserButton = new javax.swing.JButton();
        deactivateUserButton = new javax.swing.JButton();
        addTrophieButton = new javax.swing.JButton();
        playerInfoButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addUser.setBackground(new java.awt.Color(204, 255, 255));
        addUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("User");
        addUser.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, 80));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Add User");
        addUser.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 220, 80));

        addUserTF.setBackground(new java.awt.Color(255, 255, 255));
        addUserTF.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        addUserTF.setForeground(new java.awt.Color(0, 0, 0));
        addUserTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserTFActionPerformed(evt);
            }
        });
        addUser.add(addUserTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 310, 50));

        addButton.setBackground(new java.awt.Color(204, 204, 204));
        addButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        addButton.setForeground(new java.awt.Color(0, 0, 0));
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        addUser.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 210, 80));

        backButton.setBackground(new java.awt.Color(204, 0, 0));
        backButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        addUser.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 210, 80));

        getContentPane().add(addUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 510));

        addTrophy.setBackground(new java.awt.Color(204, 255, 255));
        addTrophy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("User");
        addTrophy.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 60, 50));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Add Trophy To");
        addTrophy.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 360, 80));

        addTrophyTF.setBackground(new java.awt.Color(255, 255, 255));
        addTrophyTF.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        addTrophyTF.setForeground(new java.awt.Color(0, 0, 0));
        addTrophyTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrophyTFActionPerformed(evt);
            }
        });
        addTrophy.add(addTrophyTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 280, 30));

        addTrophyButton.setBackground(new java.awt.Color(204, 204, 204));
        addTrophyButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        addTrophyButton.setForeground(new java.awt.Color(0, 0, 0));
        addTrophyButton.setText("Add Trophy");
        addTrophyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrophyButtonActionPerformed(evt);
            }
        });
        addTrophy.add(addTrophyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 290, 80));

        backButtonAT.setBackground(new java.awt.Color(153, 0, 0));
        backButtonAT.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        backButtonAT.setForeground(new java.awt.Color(255, 255, 255));
        backButtonAT.setText("Back");
        backButtonAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonATActionPerformed(evt);
            }
        });
        addTrophy.add(backButtonAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 210, 80));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Name Trophy");
        addTrophy.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 160, 50));

        nameTrophy.setBackground(new java.awt.Color(255, 255, 255));
        nameTrophy.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        nameTrophy.setForeground(new java.awt.Color(0, 0, 0));
        nameTrophy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTrophyActionPerformed(evt);
            }
        });
        addTrophy.add(nameTrophy, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 280, 30));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Trophy");
        addTrophy.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 80, 50));

        trophyType1.setBackground(new java.awt.Color(255, 255, 255));
        trophyType1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        trophyType1.setForeground(new java.awt.Color(0, 0, 0));
        trophyType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trophyType1ActionPerformed(evt);
            }
        });
        addTrophy.add(trophyType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 280, 30));

        juego.setBackground(new java.awt.Color(255, 255, 255));
        juego.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        juego.setForeground(new java.awt.Color(0, 0, 0));
        juego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juegoActionPerformed(evt);
            }
        });
        addTrophy.add(juego, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 280, 30));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Juego");
        addTrophy.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 80, 50));

        getContentPane().add(addTrophy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 510));

        deactivateUser.setBackground(new java.awt.Color(204, 255, 255));
        deactivateUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("User");
        deactivateUser.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 130, 80));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Deactivate User");
        deactivateUser.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 360, 80));

        deactivateUserTF.setBackground(new java.awt.Color(255, 255, 255));
        deactivateUserTF.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        deactivateUserTF.setForeground(new java.awt.Color(0, 0, 0));
        deactivateUserTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deactivateUserTFActionPerformed(evt);
            }
        });
        deactivateUser.add(deactivateUserTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 310, 50));

        deactivateButton.setBackground(new java.awt.Color(204, 204, 204));
        deactivateButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        deactivateButton.setForeground(new java.awt.Color(0, 0, 0));
        deactivateButton.setText("Deactivate");
        deactivateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deactivateButtonActionPerformed(evt);
            }
        });
        deactivateUser.add(deactivateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 270, 80));

        backButtonDU.setBackground(new java.awt.Color(153, 0, 0));
        backButtonDU.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        backButtonDU.setForeground(new java.awt.Color(255, 255, 255));
        backButtonDU.setText("Back");
        backButtonDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonDUActionPerformed(evt);
            }
        });
        deactivateUser.add(backButtonDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 210, 80));

        getContentPane().add(deactivateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 510));

        playerInfo.setBackground(new java.awt.Color(204, 255, 255));
        playerInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Player Info");
        playerInfo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 240, 80));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        playerInfo.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 150, 50));

        content.setColumns(20);
        content.setRows(5);
        jScrollPane1.setViewportView(content);

        playerInfo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 520, 330));

        getContentPane().add(playerInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 510));

        menu.setBackground(new java.awt.Color(204, 255, 255));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Select User");
        menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 250, 80));

        addUserButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        addUserButton.setText("Add User");
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });
        menu.add(addUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 240, 60));

        deactivateUserButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        deactivateUserButton.setText("Deactivate User");
        deactivateUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deactivateUserButtonActionPerformed(evt);
            }
        });
        menu.add(deactivateUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 240, 60));

        addTrophieButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        addTrophieButton.setText("Add Trophie");
        addTrophieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrophieButtonActionPerformed(evt);
            }
        });
        menu.add(addTrophieButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 240, 60));

        playerInfoButton.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        playerInfoButton.setText("Player Info");
        playerInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerInfoButtonActionPerformed(evt);
            }
        });
        menu.add(playerInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 240, 60));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Play Station Trophy System");
        menu.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 600, 80));

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboItemStateChanged(evt);
            }
        });
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        menu.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 140, 40));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        addUser.setVisible(true);
        menu.setVisible(false);
    }//GEN-LAST:event_addUserButtonActionPerformed

    private void deactivateUserTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deactivateUserTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deactivateUserTFActionPerformed

    private void addUserTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUserTFActionPerformed

    private void addTrophieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrophieButtonActionPerformed
        if (psn.size == 0) {
            JOptionPane.showMessageDialog(null, "No hay usuario!");
            return;
        }
        addTrophy.setVisible(true);
        menu.setVisible(false);
    }//GEN-LAST:event_addTrophieButtonActionPerformed

    private void deactivateUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deactivateUserButtonActionPerformed
        deactivateUser.setVisible(true);
        menu.setVisible(false);
    }//GEN-LAST:event_deactivateUserButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        isActivo=false;
        if(addUserTF.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Llenar todas las casillas!");
       } 
       
        try {
            if(psn.addUser(addUserTF.getText())){
                loadUsers();
                JOptionPane.showMessageDialog(null, "Se ha agregado usuario!");
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Algo salio mal "+ex.getMessage());
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        addUser.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void addTrophyTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrophyTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTrophyTFActionPerformed

    private void backButtonATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonATActionPerformed
        addTrophy.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_backButtonATActionPerformed

    private void backButtonDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonDUActionPerformed
        deactivateUser.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_backButtonDUActionPerformed

    private void playerInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerInfoButtonActionPerformed
        try {
            updateContent();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Algo salio mal "+ex.getMessage());
        }
        playerInfo.setVisible(true);
        menu.setVisible(false);
    }//GEN-LAST:event_playerInfoButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        playerInfo.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboItemStateChanged
        if (!isActivo) {
            return;
        }
        try {
            updateContent();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Algo salio mal "+ex.getMessage());
        }
    }//GEN-LAST:event_comboItemStateChanged

    private void nameTrophyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTrophyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTrophyActionPerformed

    private void addTrophyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrophyButtonActionPerformed
        if(addTrophyTF.getText().isEmpty() || nameTrophy.getText().isEmpty() || trophyType1.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Llenar todas las casillas!");
        }else{
            hashtable.trofeos tipoTrofeo = null;
            String trofeo;
            trofeo=trophyType1.getText().toLowerCase();
            if(trofeo.equals("platino")){
            tipoTrofeo=tipoTrofeo.platino;
            }else if (trofeo.equals("oro")){
                tipoTrofeo=tipoTrofeo.oro;
            }else if (trofeo.equals("plata")){
                tipoTrofeo=tipoTrofeo.plata;
            }else if(trofeo.equals("bronce")){
                tipoTrofeo=tipoTrofeo.bronce;
            }else{
                JOptionPane.showMessageDialog(null, "Trofeo no existe!");
            }
            String gameName = juego.getText();
            String trophName = nameTrophy.getText();
            String username = addTrophyTF.getText();
            try {
                psn.addTrophieTo(username, gameName, trophName, tipoTrofeo);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Algo salio mal!");
            }
        }
    }//GEN-LAST:event_addTrophyButtonActionPerformed

    private void trophyType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trophyType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trophyType1ActionPerformed

    private void juegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_juegoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_juegoActionPerformed

    private void deactivateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deactivateButtonActionPerformed
        String username = deactivateUserTF.getText();
        if(psn.users.search(username)==-1){
            JOptionPane.showMessageDialog(null, "Usuario no existe!");
        }
        try {
            psn.deactivateUsers(username);
             loadUsers();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Algo salio mal!");
        }
       
    }//GEN-LAST:event_deactivateButtonActionPerformed
    
    private void loadUsers() throws IOException {
        isActivo=false;
        entry usuarios=psn.users.inicio;
        combo.removeAllItems();

        while(usuarios!=null){
            combo.addItem(usuarios.usuario);
            usuarios=usuarios.siguiente;
        }
        isActivo=true;
        updateContent();

    }
    
    
    private void updateContent() throws IOException {
        String name = (String) combo.getSelectedItem();
        content.setText(psn.playerInfo(name));

    }
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new main().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addTrophieButton;
    private javax.swing.JPanel addTrophy;
    private javax.swing.JButton addTrophyButton;
    private javax.swing.JTextField addTrophyTF;
    private javax.swing.JPanel addUser;
    private javax.swing.JButton addUserButton;
    private javax.swing.JTextField addUserTF;
    private javax.swing.JButton backButton;
    private javax.swing.JButton backButtonAT;
    private javax.swing.JButton backButtonDU;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextArea content;
    private javax.swing.JButton deactivateButton;
    private javax.swing.JPanel deactivateUser;
    private javax.swing.JButton deactivateUserButton;
    private javax.swing.JTextField deactivateUserTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField juego;
    private javax.swing.JPanel menu;
    private javax.swing.JTextField nameTrophy;
    private javax.swing.JPanel playerInfo;
    private javax.swing.JButton playerInfoButton;
    private javax.swing.JTextField trophyType1;
    // End of variables declaration//GEN-END:variables
}
